[package]
name = "interleave"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["TristanDuncombe"]
license = "Unlicense"
description = ""
repository = "https://github.com/tristanduncombe/interleave"
keywords = ["concurrency", "proofs", "computer science"]
categories = ["utility"]
exclude = [
  ".github",
  "docs",
  "scripts",
  "tests",
  ".typstignore",
  "Justfile",
  "thumbnail.svg"
]